// auth
export const SAVE_API_TOKEN = 'SAVE_API_TOKEN'
export const DEL_API_TOKEN = 'DEL_API_TOKEN'
export const SET_UPDATING = 'SET_UPDATING'

// todo
export const TODO_ADD_ITEM = 'TODO_ADD_ITEM'
export const TODO_REMOVE_ITEM = 'TODO_REMOVE_ITEM'
export const TODO_TOGGLE_ITEM = 'TODO_TOGGLE_ITEM'
export const TODO_SAVE_LISTS = 'TODO_SAVE_LISTS'
export const TODO_SAVE_ONE_LIST = 'TODO_SAVE_ONE_LIST'
